spring:
  profiles:
    active:
    - dev
---
spring: 
  prot: 8201
spring: 
  profiles: dev
  application:
    name: microservicecloud-config-atguigu-dev
---
spring: 
  prot: 8202
spring: 
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test